### ISSUE TITLE
How to change the default I2C address?

### ISSUE THREAD

**Issue by beyonlo** [mcauser/micropython-mcp23017#11]
Hello.

I see that the MCP23017 support 8 address. From datasheet -> "[Three Hardware Address Pins to Allow Up to Eight Devices On the Bus](https://ww1.microchip.com/downloads/en/devicedoc/20001952c.pdf)"

This init the i2c from the default address 0x20, as decribed in [README.md](https://github.com/mcauser/micropython-mcp23017/blob/master/README.md):
`mcp = mcp23017.MCP23017(i2c, 0x20)`

Could you please to provide an example how to change the `MCP23017` `I2C` address? I would like to use more than one `MCP23017` on the same `I2C` bus.

Thank you in advance!

**Comment by mcauser** [comment]
Hey @beyonlo 

There are 3 pins on the chip for I2C address selection. A0, A1 and A2.
You connect them to either VCC or GND to change the address.

Most boards have onboard 0Ω resistors or solder bridges connecting them to GND, which gives the default address `0x20`.
To change address, desolder the resistor / remove the solder bridge and connect to the other side.
They often have adjacent VCC and GND pads to connect to.

If you are unable to resolder the 0Ω resistors, you can replace them with a blob of solder.
A 0Ω resistor is effectively just a wire that is pick-and-place-able.

If you module exposes A0,A1,A2 as pins, simply connect them to either VCC or GND.

This table shows which A0/A1/A2 combination results in which I2C address:
https://github.com/mcauser/micropython-mcp23017#i2c-interface

![address-selection](https://user-images.githubusercontent.com/1038959/181660060-c62b7ca0-0d1c-4da3-883f-60c287d53fbc.jpg)

**Comment by beyonlo** [comment]
Hello @mcauser 

Thank you very much for your detailed explanation. Now I understood very well.

I was thinking that could be possible to change the default address writing a different bit on the MCP23017 over I2c, without need to change physically on the hardware - some modules has that feature. 

Well, my scenario needs to change via software that addresses, I think that a good ideia is to put analogue keys to change that GND/VCC combination using GPIO from Microcontroller. If you have any tips, or comments, is welcome :)

Thank you!

**Comment by mcauser** [comment]
Generally devices that expose address selection pins don’t let you change the I2C address in software via I2C.

I’m pretty sure the MCP23017 only uses hardware pins for address selection. While you could connect A0/A1/A2 to GPIO, you’d be better off hard wiring each with a unique address, as I believe the address is determined from the A0-2 pins state once when the chip is powered on. To change address would mean having to power cycle the device.

Another option is an I2C multiplexer:
https://github.com/mcauser/micropython-tca9548a

**Comment by beyonlo** [comment]
Hello @mcauser 

Understood! Thanks to clarify.

Unfortunately that `TCA9548A` do not support high speed `I2C` (`1.7 MHz`) like as MCP23017. The `TCA9548A` support just 400KHz. But it is a good option!

Thank you very much for this great information and a ready driver for the `TCA9548A` :)
