### ISSUE TITLE
interrupt only on keypress, not keyrelease

### ISSUE THREAD

**Issue by bschymanski** [mcauser/micropython-mcp23017#4]
Hi,

i want to use your library to read keypresses.
the mcp2307 fires an interrupt when the key is pressed and also when the key is released.

Is there a way around it? I want to have the interrupt only when the key is pressed, not when it is released

**Comment by mcauser** [comment]
There is a captured register that shows the state of the pins when the INT fired. You can use this to tell if it’s the interrupt on the rising or falling pin state.

**Comment by bschymanski** [comment]
> There is a captured register that shows the state of the pins when the INT fired. You can use this to tell if it’s the interrupt on the rising or falling pin state.

yes, i can read this and it shows the correct value for the pin that triggered the interrupt and it clears the interrupt for the key press event

But the mcp2301 fires a second interrupt when the key is released, and i can't figure out how to disable or ignore this seconde interrupt

Pin Interrupt seem to be "on-change" interrupts, so the key press and the key release will each trigger an interrupt

**Comment by mcauser** [comment]
Yes, that's right. The interrupt will fire on both key down and key up.
There's 2 registers of interest to you.

The captured register - the state of the GPIO register at the time the interrupt fired
The triggered register - which pin triggered the interrupt, also clears

On both key down and key up interrupt events, read the captured register so you can tell whether the pin was high or low, and whether it's a key down or up event. Then read the triggered register and do something when the target pin triggered the interrupt and its current state is either high or low (key down or key up).

**Comment by bschymanski** [comment]
> There's 2 registers of interest to you.

Ahhh, thank you, that did the trick for me
