### ISSUE TITLE
pin order on the list interface

### ISSUE THREAD

**Issue by gkzsolt** [mcauser/micropython-mcp23017#9]
Hi @mcauser, this is a great library, thanks. One small thing, it would help if you told the (virtual) pin assignments on the list interface. You just say mcp[0], ... mcp[15] but it's not clear how this aligns with the pins on the 2 ports. I assume the order is A0,..., A7, B0, ... B7 but I'm not sure. 
Thanks,

**Comment by gkzsolt** [comment]
Ok, it's clear by reading the code. Still, it might help those who does not jump immediately at the source. Also, that port A is 0, port B 1, so you can derive a pin's list index based on a port and pin at the port. Thanks,

**Comment by mcauser** [comment]
Sorry, the docs could have been a bit clearer.

There's two 8-bit ports.
mcp[0] - mcp[7] = port A 0-7
mcp[8] - mcp[15] = port B 0-7
